version: "3.1"

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: backend # Use an image built from the specified dockerfile in the `apiNihongo` directory.
      dockerfile: Dockerfile
    ports:
      - "8090:8080" # Forward the exposed port BACK_PORT on the container to port BACK_PORT on the host machine
    restart: always
    #depends_on:
    # - db # This service depends on mysql. Start that first.
    # environment: # Pass environment variables to the service
    #  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/DB_NAME?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    # SPRING_DATASOURCE_USERNAME: DB_USERNAME
    # SPRING_DATASOURCE_PASSWORD: DB_PASSWORD

  # Frontend Service
  #app-client:
  # build:
  #  context: front-end-nihongo-redux # Use an image built from the specified dockerfile in the `front-end-nihongo` directory.
  # dockerfile: Dockerfile
  #args:
  # REACT_APP_API_BASE_URL: http://BACK_HOST_NAME:BACK_PORT
  #ports:
  # - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
  #restart: always
  #depends_on:
  # - app-server
