#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  CREATE USER $APP_DB_USER2 WITH PASSWORD '$APP_DB_PASS2';
  CREATE DATABASE $APP_DB_NAME2;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME2 TO $APP_DB_USER2;
EOSQL