server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: "1234"
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/db_data_generator
