server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://31.187.76.109:8080/realms/myrealm
          jwk-set-uri: http://31.187.76.109:8080/realms/myrealm/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: "1234"
    driver-class-name: org.postgresql.Driver
    username: root
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/db_data_generator
